server {
    server_name estora.localhost;

    root /var/www/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2|ttf|eot|otf|ttf|ttc|map)$ {
        expires 6M;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }

    location ~* \.(css|js)$ {
        expires 1M;
        access_log off;
    }

    location ~ ^/(storage|bootstrap/cache)/ {
        deny all;
    }

   location ~ /\.(?!well-known).* {
        deny all;
    }

   client_max_body_size 100M;

   add_header X-Frame-Options "SAMEORIGIN";
   add_header X-Content-Type-Options "nosniff";
   add_header X-XSS-Protection "1; mode=block";

   error_page 404 /index.php;

   access_log /var/log/nginx/laravel_access.log;
   error_log /var/log/nginx/laravel_error.log;
}
